function out1 = kernel_d2f_zerolim(k)
%KERNEL_D2F_ZEROLIM
%    OUT1 = KERNEL_D2F_ZEROLIM(K)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    07-Mar-2025 15:40:37

out1 = k.^4.*(-1.0./3.0);
end
