function out1 = kernel_d3f_zerolim(k)
%KERNEL_D3F_ZEROLIM
%    OUT1 = KERNEL_D3F_ZEROLIM(K)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    07-Mar-2025 15:40:38

out1 = 0.0;
end
