function out1 = kernel_d2f(k,r)
%KERNEL_D2F
%    OUT1 = KERNEL_D2F(K,R)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    07-Mar-2025 15:40:37

t2 = k.*r;
t3 = sin(t2);
out1 = -k.*1.0./r.^3.*(t3.*-2.0+t2.^2.*t3+t2.*cos(t2).*2.0);
end
