function out1 = kernel_d0f(k,r)
%KERNEL_D0F
%    OUT1 = KERNEL_D0F(K,R)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    07-Mar-2025 15:40:36

out1 = (k.*sin(k.*r))./r;
end
