function out1 = kernel_d3f(k,r)
%KERNEL_D3F
%    OUT1 = KERNEL_D3F(K,R)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    07-Mar-2025 15:40:38

t2 = k.*r;
t3 = cos(t2);
t4 = sin(t2);
out1 = -k.*1.0./r.^4.*(t4.*6.0-t2.*t3.*6.0-t2.^2.*t4.*3.0+t2.^3.*t3);
end
