function errest = kernel_d1f_series_err(k,r)
%KERNEL_D1F_SERIES_ERR
%    ERREST = KERNEL_D1F_SERIES_ERR(K,R)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    07-Mar-2025 15:40:37

errest = (abs(k.^2.*r.^2-1.258e+3).*abs(k).^36.*abs(r).^33)./3.823264747562874e+41;
end
