function errest = kernel_d3f_series_err(k,r)
%KERNEL_D3F_SERIES_ERR
%    ERREST = KERNEL_D3F_SERIES_ERR(K,R)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    07-Mar-2025 15:40:38

errest = (abs(k.^2.*r.^2.*3.7e+1-4.641e+4).*abs(k).^38.*abs(r).^33)./1.491073251549521e+43;
end
