function out1 = kernel_d1f(k,r)
%KERNEL_D1F
%    OUT1 = KERNEL_D1F(K,R)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    07-Mar-2025 15:40:37

t2 = k.*r;
out1 = -k.*1.0./r.^2.*(sin(t2)-t2.*cos(t2));
end
