function errest = kernel_d2f_series_err(k,r)
%KERNEL_D2F_SERIES_ERR
%    ERREST = KERNEL_D2F_SERIES_ERR(K,R)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    07-Mar-2025 15:40:37

errest = (abs(k.^2.*r.^2.*3.5e+1-4.1514e+4).*abs(k).^36.*abs(r).^32)./3.823264747562874e+41;
end
