function out1 = kernel_d1f_zerolim(k)
%KERNEL_D1F_ZEROLIM
%    OUT1 = KERNEL_D1F_ZEROLIM(K)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    07-Mar-2025 15:40:37

out1 = 0.0;
end
