function errest = kernel_d0f_series_err(k,r)
%KERNEL_D0F_SERIES_ERR
%    ERREST = KERNEL_D0F_SERIES_ERR(K,R)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    07-Mar-2025 15:40:37

errest = (abs(k.^2.*r.^2-1.19e+3).*abs(k).^34.*abs(r).^32)./1.033314796638614e+40;
end
