function proxy_charges = points2proxy(points, charges, p)
% Form proxy charges for points scaled to [-1,1]^3
    [~, V] = approx.chebvander(p);
    Vi = inv(V);
    proxy_charges = approx.chebevalmat3_trans_apply(...
        points(:, 1), ...
        points(:, 2), ...
        points(:, 3), ...
        p, charges, Vi);
end


